### ISSUE TITLE
react-animation: Better support hot reloading where refs become null

### ISSUE THREAD

**Issue by ThaNarie** [mediamonks/transition-component#96]
I've found two places that break hot reloading:

1. In `AnimationMap.set` we check for null-refs to prevent stored animations ending up in a void without anyone realising something went wrong, and a ref was never set.
2. In `assertAndUnwrapRefs` we change the TS type, and fail if any refs are null.

Both cases break hot reloading, meaning that the dev will see an error on screen (and in console), and has to reload the page manually.

## AnimationMap.set

Here we can leave out the error, and use an error log instead, since it's just to inform the user.

Downside is that we don't want to flood the console with error logs in valid cases (during hot reloading).
Here we _could_ keep track of which refs ever had a value set, and ignore this error log when it's emptied (assuming this is just temporary, and on purpose).

## assertAndUnwrapRefs

The reason it exists is to not continue the rest of the function in case any refs are null, and to inform the user.
Instead of bailing out with an error, we could also let the user handle it more elegantly, something like:

```ts
const { isValid, self, item } = assertAndUnwrapRefs(refs);
if (!isValid) return gsap.timeline();
```

We still want to show an error log, but ideally not in a way that floods the console. In the same was as with the AnimationMap, we could detect if we've already validated the `refs` object once correctly, and forgo any logs if that's the case.

**Comment by leroykorterink** [comment]
@ThaNarie changes in #208 will prevent the error in `AnimationsMap.set`. We're not trying to set an animation for a nullable key anymore.

**Comment by leroykorterink** [comment]
`assertAndUnwrapRefs` is part of @mediamonks/react-hooks, I'll make an issue for this problem in that repository.
